### ISSUE TITLE
User Guide suggestion

### ISSUE THREAD

**Issue by lj-allen** [stfc-sciml/ffsas#1]
Hi all,

I was reading the user guide and would like to suggest changing or altering the font slightly, especially for the equations, to make everything clearer. For example, upper-case I and lower-case l look identical, and when they're in the same equation it can be difficult to interpret, especially if (like me) you're new to the math.

Thanks,
Lisa

**Comment by kuangdai** [comment]
Thanks Lisa. I have changed the font family.
