### ISSUE TITLE
1D scattering curve/plot for ellipsoid model

### ISSUE THREAD

**Issue by lj-allen** [stfc-sciml/ffsas#2]
Hello,

Is it possible to plot the output of calculating the intensity truth (q vs. I_true) as a 1D scattering curve instead of a 2D image/heat plot for the ellipsoid model?

Many thanks,
Lisa

**Comment by kuangdai** [comment]
Hi Lisa,

To get the 1D plot, you need to integrate the image over the azimuthal direction. But this is not a task of FFSAS.
